imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        # add "_test" behind db name
        dbname: '%database_name%_test'

liip_functional_test: ~

swiftmailer:
    # change the spool as disabling delivery doesn't stop spooling to a file
    spool: { type: memory }
    disable_delivery: true
#    delivery_address: admin@xmmedia.com
#    delivery_whitelist:
#        - '/@xmmedia\.com$/'