imports:
    - { resource: config_dev.yml }
    - { resource: services_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: MOCKSESSID
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        driver: pdo_sqlite
        path:   '%kernel.cache_dir%/test.db'
        charset: UTF8
        default_table_options:
            charset: UTF8
            collation: UTF8

liip_functional_test:
    cache_sqlite_db: true

swiftmailer:
    # change the spool as disabling delivery doesn't stop spooling to a file
    spool: { type: memory }
    disable_delivery: true
#    delivery_address: admin@xmmedia.com
#    delivery_whitelist:
#        - '/@xmmedia\.com$/'

nelmio_alice:
    locale: 'en_CA'

fidry_alice_data_fixtures:
    db_drivers:
        doctrine_orm: true