imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_CA
    web_root: '%kernel.project_dir%/html'
    # upload paths
    upload.private.root_dir: '%kernel.project_dir%/var/uploads'
    upload.public.root_dir: '%web_root%/uploads'

framework:
    #esi:             ~
    translator:      { fallbacks: ['%locale%'] }
    secret:          '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  '%locale%'
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/html/build/manifest.json'

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        global_js_data: '@AppBundle\DataProvider\GlobalJsData'
        ga_tracking_id: '%ga_tracking_id%'
        # needed because it's used in the menu to generate the link to the previous user filters
        user_filter:    '@xm_user_admin.filter.user'
    form_themes:
        - 'Form/fields.html.twig'
#        - 'VichUploaderBundle:Form:fields.html.twig'

knp_paginator:
    template:
        pagination: pagination.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  utf8mb4
        # @todo-symfony update if required
        server_version: '5.7'
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: '%kernel.root_dir%/DoctrineMigrations'
    namespace: Application\Migrations
    table_name: migration_versions
    name: Migrations

# Swiftmailer Configuration
swiftmailer:
    transport:  '%mailer_transport%'
    host:       '%mailer_host%'
    encryption: '%mailer_encryption%'
    port:       '%mailer_port%'
    username:   '%mailer_user%'
    password:   '%mailer_password%'
    spool:
        type: file
        path: '%kernel.project_dir%/var/mail_spool'

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    # custom forms below come from http://stackoverflow.com/a/21064627/5441
#    registration:
#        form:
#            type: AppBundle\Form\RegistrationType
#            validation_groups: [ Registration ]
#    profile:
#        form:
#            type: AppBundle\Form\ProfileType
#            validation_groups: [ Profile ]
    from_email:
        address:        '%from_email%'
        sender_name:    '%from_name%'

#vich_uploader:
#    db_driver: orm
#
#    mappings:
#        photo:
#            upload_destination: '%upload.private.root_dir%'
#            namer:              vich_uploader.namer_uniqid
#            inject_on_load:     true

#liip_imagine:
#    resolvers:
#        default:
#            web_path:
#                web_root: '%web_root%'
#                cache_prefix: "media"
#
#    loaders:
#        default:
#            filesystem:
#                data_root: '%upload.private.root_dir%'
#
#    filter_sets:
#        cache: ~
#        photo_thumbnail:
#            data_loader: ???
#            quality: 70
#            filters:
#                upscale: { min: [540, 400] }
#                thumbnail: { size: [540, 400], mode: outbound }
#        photo_og:
#            data_loader: ???
#            quality: 70
#            filters:
#                upscale: { min: [1200, 500] }
#                relative_resize:
#                    widen: 1200
#        photo:
#            data_loader: fund_photo
#            quality: 70
#            filters:
#                relative_resize:
#                    widen: 900

accelerator_cache:
    host: '%router.request_context.scheme%://%router.request_context.host%'
    web_dir: '%web_root%'
