security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: 'argon2i'

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /admin
                use_referer: true
                success_handler: xm_security.auth.authentication_success_handler
                login_path:   fos_user_security_login
                failure_path: fos_user_security_login
                check_path:   fos_user_security_check
            logout:
                path:   fos_user_security_logout
                # @todo-symfony change to correct path
                target: fos_user_security_login
#                delete_cookies:
#                    cart: { path: null, domain: null }
            anonymous: true
            logout_on_user_change: true

    access_control:
        # @todo-symfony
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
