# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
# twig extensions: http://twig.sensiolabs.org/doc/extensions/index.html
#    app.twig_extension.intl:
#        class: Twig_Extensions_Extension_Intl
#        public: false
#        tags:
#            - { name: twig.extension }
#
#    app.twig_extension.text:
#        class: Twig_Extensions_Extension_Text
#        public: false
#        tags:
#            - { name: twig.extension }

# app services
    # general listeners
    app.maintenance:
        class: AppBundle\EventListener\MaintenanceListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    gedmo_doctrine_extensions.listener.ip_traceable:
        class: Gedmo\IpTraceable\IpTraceableListener
        arguments: ["@annotation_reader"]
        tags:
            - { name: doctrine.event_subscriber, method: setAnnotationReader }

    app.event_listener.ip_trace:
        class: AppBundle\EventListener\IpTraceSubscriber
        arguments: ["@gedmo_doctrine_extensions.listener.ip_traceable", "@request_stack"]
        tags:
            - { name: kernel.event_subscriber }

# assets
    assets.version_strategy:
        class: XM\AssetVersionBundle\Asset\VersionStrategy\FileModifiedTimestampVersionStrategy
        arguments: ['%web_root%']